CarWorkShop/Controllers/OwnerController.cs
using CarWorkShop.Models.ViewModel.Owner;
using CarWorkShop.Service.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace CarWorkShop.Controllers
{
    public class OwnerController : Controller
    {

        private readonly IOwnerService _ownerService;

        public OwnerController(IOwnerService ownerService)
        {
            _ownerService = ownerService;
        }

        public async Task<IActionResult> GetOwners()
        {
            var response = await _ownerService.GetOwners();
            if (response.StatusCode == Models.Enum.StatusCode.OK)
            {
                return View(response.Data);
            }

            return RedirectToAction("Index", "Home");
        }

        public async Task<IActionResult> Delete(int id)
        {
            var response = await _ownerService.Delete(id);
            if (response.StatusCode == Models.Enum.StatusCode.OK)
            {
                return RedirectToAction("GetOwners");
            }
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public IActionResult CreateOwner() => View();

        [HttpPost]
        public async Task<IActionResult> CreateOwner(OwnerViewModel viewModel)
        {
            var response = await _ownerService.Create(viewModel);
            
            if (response.StatusCode == Models.Enum.StatusCode.OK)
            {
                return RedirectToAction("GetOwners");
            }
            return View();
        }


        public IActionResult Index()
        {
            return View();
        }
    }
}

CarWorkShop/Controllers/ProfileController.cs
using CarWorkShop.Models.ViewModel.Profile;
using CarWorkShop.Service.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CarWorkShop.Controllers
{
    public class ProfileController : Controller
    {

        private readonly IProfileService _profileService;

        public ProfileController(IProfileService profileService)
        {
            _profileService = profileService;
        }

        [Authorize]
        public async Task<IActionResult> Detail()
        {
            var login = User.Identity.Name;
            var  response = await _profileService.GetProfile(login);
            if (response.StatusCode == Models.Enum.StatusCode.OK)
            {
                return View(response.Data);
            }
            return View();
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Save(ProfileViewModel viewModel)
        {
            ModelState.Remove("Login");
            if (ModelState.IsValid)
            {
                 await _profileService.Save(viewModel);
            }
            return RedirectToAction("Detail");
        }
    }
}

CarWorkShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CarWorkShop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CarWorkShop.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/card.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/paragraph.css" asp-append-version="true"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/5.3.0/css/bootstrap.min.css">
    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/navbars/">


</head>
<body style="overflow: auto;">
    <header>
         <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
               @if (!User.Identity.IsAuthenticated)
            {
                 <div class="container-fluid">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CarWorkShop</a>
                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-sm-0">
                            <li class="nav-item">
                                 <a class="nav-link active" asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
                            </li>

                            <li class="nav-item dropdown">
                                     <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown" aria-expanded="false">Аккаунт</a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Account" asp-action="Login">Авторизация</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Account" asp-action="Register">Регистрация</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            }
            @if (User.Identity.IsAuthenticated)
            {
                 <div class="container-fluid">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CarWorkShop</a>
                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-sm-0">
                            <li class="nav-item">
                                 <a class="nav-link active" asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
                            </li>
                            @if (User.IsInRole("Admin"))
                            {
                                 <li class="nav-item dropdown">
                                     <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown" aria-expanded="false">Админ</a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Owner" asp-action="GetOwners">Список пользователей</a></li>
                                </ul>
                                 </li>
                            }
                        </ul>
                        
                        <div style="position:absolute; right:0; display: flex; justify-content:center;">
                            <a asp-controller="Profile" asp-action="Detail">
                                <svg style="color: black;" xmlns="http://www.w3.org/2000/svg" width="44" height="44" fill="currentColor" class="bi bi-person-fill" viewBox="0 0 16 16">
                                    <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
                                </svg>
                            </a>
                            <form method="post" asp-controller="Account" asp-action="Logout">
                                 <input class="btn btn-close" value=""  style="margin-right:10px; padding: 10px; background-color:white; width:24px; height:24px; border-radius:3px;" type="submit">
                             </form>
                    
                            <form role="search" style="margin-right:10px;">
                                <input class="form-control" type="search" placeholder="Поиск" style="padding: 10px;"  aria-label="Search">
                            </form>
                        </div>
                    </div>
                </div>
            }
          </nav>
    </header>

    <div class="container follcontent" >
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CarWorkShop - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
   @* @await RenderSectionAsync("Scripts", required: false)*@
    @await RenderSectionAsync("pageScripts", required: false)
</body>
</html>