CarWorkShop/Controllers/RecordController.cs
using CarWorkShop.Models.ViewModel.Record;
using CarWorkShop.Service.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace CarWorkShop.Controllers
{
    public class RecordController : Controller
    {
        private readonly IRecordService _recordService;
        private readonly IOwnerService _ownerService;
        private readonly IProfileService _profileService;
        private readonly ILogger<RecordController> _logger;

        public RecordController(IRecordService recordService, ILogger<RecordController> logger, IOwnerService ownerService, IProfileService profileService)
        {
            _recordService = recordService;
            _logger = logger;
            _ownerService = ownerService;
            _profileService = profileService;
        }

        [HttpGet]
        [Authorize]
        public IActionResult GetRecords()
        {
            var userName = User.Identity.Name;
            var records =  _recordService.GetRecords(userName);
            if (records.StatusCode == Models.Enum.StatusCode.OK)
            {
                return View(records.Data);
            }

            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> GetRecord()
        {
            
            var records = await _recordService.GetRecord(User.Identity.Name);
            if (records.StatusCode == Models.Enum.StatusCode.OK)
            {
                return View(records.Data);
            }

            return RedirectToAction("Error");
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var response = await _recordService.Delete(id);
            if (response.StatusCode == Models.Enum.StatusCode.OK)
            {
                _logger.LogInformation($"Была удалена запись под номером \"{response.Data}\" пользователем ////");
                return RedirectToAction("GetRecords");
            }

            return View("Error", $"{response.Description}");
        }

        [HttpGet]
        public IActionResult CreateRecord()
        {
            
            var profile = _profileService.GetProfile(User.Identity.Name);
            var model = new RecordViewModel()
            {
                Login = User.Identity.Name,
                FirstName = profile?.Result.Data.FirstName,
                LastName = profile.Result.Data.LastName,
                MiddleName = profile.Result.Data.MiddleName,
                Age = profile.Result.Data.Age,
                DateTime = DateTime.Now.ToLongDateString()

            };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> CreateRecord(RecordViewModel viewModel)
        {
            //byte[] imageData;
            //using (var binaryReader = new BinaryReader(model.Avatar.OpenReadStream()))
            //{
            //    imageData = binaryReader.ReadBytes((int)model.Avatar.Length);
            //}
            viewModel.Login = User.Identity.Name;
            if (ModelState.IsValid)
            {
                var response = await _recordService.Create(viewModel, null);

                _logger.LogInformation($"Была добавлена запись под номером \"{response.Data.Id}\" пользователем {User.Identity.Name}");
                return RedirectToAction("GetRecords");
            }
           
            return View();

           
        }

        [HttpPost]
        public async Task<IActionResult> UpdateRecord(int id, RecordViewModel viewModel)
        {
            //byte[] imageData;
            //using (var binaryReader = new BinaryReader(model.Avatar.OpenReadStream()))
            //{
            //    imageData = binaryReader.ReadBytes((int)model.Avatar.Length);
            //}
            var response = await _recordService.Update(id, viewModel);
            if (response!= null)
            {
                _logger.LogInformation($"Была обновлена запись под номером \"{response.Data}\" пользователем ////");
                return RedirectToAction("GetRecords");
            }
            
            return View();


        }
    }
}

CarWorkShop/Views/Record/CreateRecord.cshtml
@model CarWorkShop.Models.ViewModel.Record.RecordViewModel

@{
    ViewData["Title"] = "Создание записи";
  
}

<div class="content" style="max-width:350px; justify-content:center;">
    <div class="card col-md-12">
    <form asp-controller="Record" asp-action="CreateRecord" method="post">
        <div asp-validation-summary="ModelOnly" style="font-size:23px; font-family:Impact" class="text-danger text-center"></div>
        <div class="mb-3 input-group">
            <label class="form-label">Имя</label>
            <input type="text" asp-for="FirstName" readonly class="form-control"/>
        </div>
        <div class="mb-3 input-group">
            <label class="form-label">Фамилия</label>
            <input type="text" asp-for="LastName" readonly  class="form-control" />
        </div>
        <div class="mb-3 input-group">
            <label class="form-label">Отчество</label>
            <input type="text" asp-for="MiddleName" readonly class="form-control" />
        </div>
         <div class="mb-3 input-group">
            <label class="form-label">Возраст</label>
            <input type="text" asp-for="Age" readonly class="form-control" />
        </div>
        <div class="mb-3 input-group">
            <label class="form-label">Время</label>
            <input type="datetime" asp-for="DateTime" readonly  class="form-control" />
        </div>
        <div class="mb-3 input-group">
            <label class="form-label">Модель автомобиля</label>
            <input type="text" asp-for="Model" class="form-control" />
        </div>
        <div class="mb-3 input-group">
            <label class="form-label">Марка Автомобиля</label>
            <input type="text" asp-for="Mark" class="form-control" />
        </div>
         <div class="mb-3 input-group">
            <label class="form-label">Регистрационный номер Автомобиля</label>
            <input type="text" asp-for="CarNumber" class="form-control" />
        </div>
         <div class="mb-3 input-group">
            <label class="form-label">Жалобы</label>
            <input type="text" asp-for="Complaint" class="form-control" />
        </div>
        <div class="mb-3 input-group">
           <div class="active">
                <button class="btn btn-primary float-right" type="submit">Отправить</button>
                  <a asp-controller="Record" asp-action="GetRecords">Список всех записей</a>
           </div>
        </div>
    </form>
</div>
</div>

CarWorkShop/Views/Record/GetRecord.cshtml
@*@model CarWorkShop.Models.ViewModel.Record.RecordViewModel*@

@*@if (@Model != null || @Model.Count > 0)
{
     <div class="table-responsive">
    <table class="table table-striped">
        <thead class="thead-dark">
            <tr>
                <th>Айди</th>
                <th>Жалобы</th>
                <th>Марка автомобиля</th>
                <th>Модель автомобиля</th>
                <th>Номер автомобиля</th>
                <th>Дата создания</th>
                <th>Имя клиента</th>
                <th>Фамилия клиента</th>
                <th>Отчество клиента</th>
                <th>Возраст клиента</th>
                <th>#</th>
                <th>#</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var record in @Model)
            {
                <tr>
                    <td>@record.Id</td>
                    <td>@record.Complaint</td>
                    <td>@record</td>
                    <td>@record.Car.Model</td>
                    <td>@record.Car.CarNumber</td>
                    <td>@record.DateTime.ToString("yyyy-MM-dd")</td>
                    <td>@record.Profile.FirstName</td>
                    <td>@record.Profile.LastName</td>
                    <td>@record.Profile.MiddleName</td>
                    <td>@record.Profile.Age</td>
                    <td>
                        <form asp-controller="Record" asp-action="Delete" asp-route-id="@record.Id" method="post">
                            <button type="submit" class="btn btn-sm btn-danger">
                                Удалить
                            </button>
                        </form>
                    </td>
                     <td>
                        <button class="btn btn-primary edit-btn" data-toggle="modal" data-target="#editModal">Редактировать</button>
                    </td>
                </tr>
                    <div class="modal" id="editModal">
                          <div class="modal-dialog">
                            <div class="modal-content">
                              <div class="modal-header">
                                <h5 class="modal-title">Редактировать запись</h5>
                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                              </div>
                              <div class="modal-body">
                                <form method="post" action="/Record/Edit">
                                  <!-- форма для редактирования строки -->
                                </form>
                              </div>
                            </div>
                          </div>
                    </div>
            }
        </tbody>
    </table>
</div> 
}

else
{
    <p>Список пуст(:)</p>
}*@

CarWorkShop/Views/Record/GetRecords.cshtml
@using CarWorkShop.Models.Entity
@*@using CarWorkShop.Models.ViewModel.Record*@
@model List<Record>



   
@if (@Model != null || @Model.Count > 0)
{
     <div class="table-responsive">
    <table class="table table-striped">
        <thead class="thead-dark">
            <tr>
                <th>Айди</th>
                <th>Жалобы</th>
                <th>Марка автомобиля</th>
                <th>Модель автомобиля</th>
                <th>Номер автомобиля</th>
                <th>Дата создания</th>
                <th>Имя клиента</th>
                <th>Фамилия клиента</th>
                <th>Отчество клиента</th>
                <th>Возраст клиента</th>
                <th>#</th>
                <th>#</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var record in @Model)
            {
                <tr>
                    <td>@record.Id</td>
                    <td>@record.Complaint</td>
                    <td>@record.Car.Mark</td>
                    <td>@record.Car.Model</td>
                    <td>@record.Car.CarNumber</td>
                    <td>@record.DateTime.ToString("yyyy-MM-dd")</td>
                    <td>@record.Owner?.Profile?.FirstName</td>
                    <td>@record.Owner?.Profile?.LastName</td>
                    <td>@record.Owner?.Profile?.MiddleName</td>
                    <td>@record.Owner?.Profile?.Age</td>
                    <td>
                        <form asp-controller="Record" asp-action="Delete" asp-route-id="@record.Id" method="post">
                            <button type="submit" class="btn btn-sm btn-danger">
                                Удалить
                            </button>
                        </form>
                    </td>
                     <td>
                        <button class="btn btn-primary edit-btn" data-toggle="modal" data-target="#editModal">Редактировать</button>
                    </td>
                </tr>
                    <div class="modal" id="editModal">
                          <div class="modal-dialog">
                            <div class="modal-content">
                              <div class="modal-header">
                                <h5 class="modal-title">Редактировать запись</h5>
                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                              </div>
                              <div class="modal-body">
                                <form method="post" action="/Record/Edit">
                                  <!-- форма для редактирования строки -->
                                </form>
                              </div>
                            </div>
                          </div>
                    </div>
            }
        </tbody>
    </table>
</div> 
}

else
{
    <p>Список пуст(:)</p>
}
<div>
    <a class="flex-sm-fill text-sm-center" asp-controller="Record" asp-action="CreateRecord">Создать запись</a>
</div>